name: CI/CD for ESP32

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git clone -b v4.2 --recursive https://github.com/espressif/esp-idf.git esp-idf-v4.2
        ./esp-idf-v4.2/install.sh
        echo "source $(pwd)/esp-idf-v4.2/export.sh" >> $GITHUB_ENV

    - name: Cache ESP-IDF dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.espressif
          ~/esp
        key: ${{ runner.os }}-esp-idf-${{ hashFiles('**/idf_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-esp-idf-

    - name: Install ESP32 dependencies
      run: |
        sudo apt-get install -y gcc make flex bison gperf python3 python3-pip python3-setuptools python3-serial python3-click python3-pyparsing python3-cryptography python3-future python3-pyelftools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
        pip3 install esptool

    - name: Build firmware
      run: |
        source $GITHUB_ENV
        idf.py build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: build/

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: firmware
        path: build/

    - name: Sync built firmware to S3
      run: |
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET }}/firmware/

    - name: Notify MQTT broker
      run: |
        pip3 install paho-mqtt
        python3 notify_mqtt.py
